title: "Awesome Indexer Example"
sources:
- name: "IIPC Web Archiving Collection"
  type: zotero
  library_type: group
  library_id: 2271741
- name: "iPRES Zotero Collection"
  type: zotero
  library_type: group
  library_id: "5564150"
- name: "Ethan Gates's Emulation Library"
  type: zotero
  library_type: user
  library_id: 8195999
  collection_id: "ERZIYJ3T"
- name: "Software Preservation library"
  type: zotero
  library_type: user
  library_id: 5791319
- name: "Awesome Web Archiving"
  type: awesome-list
  url: "https://raw.githubusercontent.com/iipc/awesome-web-archiving/refs/heads/main/README.md"
- name: "Awesome Digital Preservation"
  type: awesome-list
  view_url: "https://github.com/digipres/awesome-digital-preservation/blob/main/README.md?plain=1"
  url: "https://github.com/iipc/awesome-web-archiving/raw/refs/heads/main/README.md"
